apiVersion: apps/v1
kind: Deployment
metadata:
  name: governance-policy-syncer
spec:
  replicas: 1
  selector:
    matchLabels:
      name: governance-policy-syncer
  template:
    metadata:
      labels:
        name: governance-policy-syncer
        app: governance-policy-framework
    spec:
      securityContext:
        runAsNonRoot: true
      serviceAccountName: governance-policy-syncer
      containers:
        - name: governance-policy-syncer
          image: quay.io/open-cluster-management/governance-policy-syncer:latest
          command:
            - governance-policy-syncer
          args:
            - "--hub-cluster-configfile=/var/run/klusterlet/kubeconfig"
            - "--enable-lease=true"
            - "--log-level=2"
            - "--v=0"
          imagePullPolicy: Always
          volumeMounts:
            - name: klusterlet-config
              mountPath: /var/run/klusterlet
          env:
            - name: WATCH_NAMESPACE
              value: managed
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "governance-policy-syncer"
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8082
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: klusterlet-config
          secret:
            secretName: hub-kubeconfig
            defaultMode: 420
