apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: governance-policy-syncer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: governance-policy-syncer
subjects:
- kind: ServiceAccount
  name: governance-policy-syncer
  namespace: open-cluster-management-agent-addon
